{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $namespace := .Values.namespace | default .Release.Namespace }}

{{- if .Values.clusterExternalSecret.enabled }}
{{- $secret := .Values.clusterExternalSecret.secret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ $secret.name }}
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
  {{- if $secret.annotations }}
  annotations:
    {{- toYaml $secret.annotations | nindent 4 }}
  {{- end}}
spec:
  externalSecretName: {{ $secret.exteranlSecretName }}
  namepaceSelector:
    {{- toYaml $secret.namespaceSelector | nindent 4 }}
  {{- if $secret.refreshTime }}
  refreshTime: {{ $secret.refreshTime }}
  {{- end }}
  {{- if $secret.refreshInterval }}
  refreshInterval: {{ $secret.refreshInterval }}
  {{- end }}
  externalSecretSpec:
    secretStoreRef:
      name: {{ $secret.externalSecretSpec.secretStoreRef.name }}
      kind: {{ $secret.externalSecretSpec.secretStoreRef.kind }}
    target:
      creationPolicy: "Owner"
      {{- if $secret.externalSecretSpec.target }}
      {{- toYaml $secret.externalSecretSpec.target | nindent 6}}
      {{- end }}
    {{- if $secret.externalSecretSpec.data }}
    data:
    {{- toYaml $secret.externalSecretSpec.data | nindent 6 }}
    {{- end }}
    {{- if $secret.externalSecretSpec.dataFrom }}
    dataFrom:
    {{- toYaml $secret.externalSecretSpec.dataFrom | nindent 6 }}
    {{- end}}
{{- end }}
---
{{- if .Values.ExternalSecret.enabled }}
{{- range $i, $secret := .Values.ExternalSecret.secrets}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $namespace }}
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
  {{- if $secret.annotations }}
  annotations:
    {{- toYaml $secret.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if $secret.refreshInterval }}
  refreshInterval: {{ $secret.refreshInterval }}
  {{- end }}
  secretStoreRef:
    name: {{ $secret.secretStoreRef.name }}
    kind: {{ $secret.secretStoreRef.kind }}
  target:
    creationPolicy: "Owner"
    {{- if $secret.target }}
    {{- toYaml $secret.target | nindent 4 }}
    {{- end }}
  {{- if $secret.data }}
  data:
  {{- toYaml $secret.data | nindent 4 }}
  {{- end }}
  {{- if $secret.dataFrom }}
  dataFrom:
  {{- toYaml $secret.dataFrom | nindent 4 }}
  {{- end}}
{{- end }}
{{- end }}
