{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}


{{- if .Values.clusterSecretStore.enabled }}
{{- $config := .Values.clusterSecretStore.config }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $config.name }}
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
  {{- if $config.annotations }}
  annotations:
    {{- toYaml $config.annotations | nindent 4 }}
  {{- end }}
spec:
  provider: 
  {{- toYaml $config.provider | nindent 4 }}
{{- end}}